name: Run Tests and Merge to Main

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
          echo ${{github.event.pull_request.base.ref}}
          echo ${{github.event.pull_request.head.ref}}
