name: Build and Commit Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Commit changes
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your.email@example.com'
        git add .
        git commit -m "Automated build for PR ${GITHUB_REF}"
        git push origin HEAD:${GITHUB_REF}
