name: Run Tests and Merge to Main

on:
  pull_request:
    types:
      - opened
    branches:
      - "main"

jobs:
  build-and-merge:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: echo
        run: echo "${{github.event.pull_request.base}}"

      - name: Merge to main
        if: startsWith(github.event.pull_request.base, 'zeroheight-tokens-')
        uses: actions/github-script@0.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = await github.repos.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: context.payload.pull_request.head.ref,
              head: context.payload.pull_request.head.ref
            })
            console.log(result)
